{
 "title": "Ich Data Intelligence",
 "tags": [
  "ich",
  "data",
  "intelligence"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1s",
 "panels": [
  { "title": "Hardware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "System",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "%",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "glances_cpu_used" }
     ]
    },
    {
     "alias": "Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "15 min",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "glances_cpu_load" }
     ]
    },
    {
     "alias": "Containers",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "%",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "glances_containers_cpu_used" }
     ]
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "RAM",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "%",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "glances_ram_used_percent" }
     ]
    },
    {
     "alias": "Swap",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "%",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "glances_swap_used_percent" }
     ]
    }
   ]
  },
  { "title": "Face Detection Demo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Frames Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "FPS" }
   ],
   "targets": [
    {
     "alias": "Face Detection Demo",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "frames_per_second",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": " application", "operator": "=", "value": "face_recognition_demo" }
     ]
    }
   ]
  },
  {
   "title": "Frame Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "Face Detection Demo",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "frame_time",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": " application", "operator": "=", "value": "face_recognition_demo" }
     ]
    }
   ]
  },
  {
   "title": "Multi Camera Multi Person Tracking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true
  },
  {
   "title": "Frames Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "FPS" }
   ],
   "targets": [
    {
     "alias": "Multi Camera Multi Person Tracking",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "frames_per_second",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": " application",
       "operator": "=",
       "value": "dlrs_multi_camera_multi_person_tracking"
      }
     ]
    }
   ]
  },
  {
   "title": "Person Identification",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "person_identification",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": " application",
       "operator": "=",
       "value": "dlrs_multi_camera_multi_person_tracking"
      }
     ]
    }
   ]
  }
 ]
}